### PR TITLE
Describe mandatory --lock-file-dir / lock_file_dir configuration

### PR DESCRIPTION
**Pull request by cfi-gb**
**What**:

Should be self-explanatory

**Why**:

See e.g. https://github.com/Atomicorp/openvas/issues/25#issuecomment-687884201

**How**:

Not required

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

### CODE REVIEW

**Review by bjoernricks — COMMENTED** [review]
Is this really mandatory? Personally I never expected that the lock file needs to be the same in gvmd an ospd-openvas and would consider this a big.

**Comment by cfi-gb** [comment]
@timopollmeier and/or @jjnicola might be able to tell more but my last information was that all components should / need to use the very same lock file.

**Comment by ramsaut** [comment]
If the installation prefix is not empty, ospd-openvas still tries to create the lock file in /var/run/ospd/feed-update.lock instead of e.g. /opt/gvm/var/run/ospd/feed-update.lock and the configuration option is mandatory for the sync to work, because the /var/run/ospd/ directory does not exist and is not created.

**Comment by jjnicola** [comment]
Currently, to not overlap feed related process, the path must be the same one used by greenbone-nvt-sync and gvmd. Of course there is place for improvements. While some default configuration changes can be done in the near future, a more invasive change like reducing the dependency on the lock file of other modules will be possible schedule for the next mayor release.

**Review by jjnicola — APPROVED** [review]

**Pull request merged**
