### PR TITLE
Variable inheritance problem

### PR DESCRIPTION
**Pull request by huifeidexingyuner**
Problems in compiling and using ospD OpenVAS

### CODE REVIEW

**Comment by bjoernricks** [comment]
I really don't think your PR is correct. self.ctx is a property and must be used to get the redis context for the nvticache.

**Comment by huifeidexingyuner** [comment]
I installed osp-openvas on a pure ubuntu18.4 (python3.6) system and encountered the following problems, because self.ctx is None, and it was ok after I modified it.
---------------------------------------------------------------------------------------------------------
..... .. "/usr/local/lib/python3.6/dist-packages/ospd_openvas-20.4a1-py3.6.egg/ospd_openvas/daemon.py", line 1774, in main
Mar  5 19:52:32 ubuntu le "/usr/local/lib/python3.6/dist-packages/ospd-20.4a1-py3.6.egg/ospd/main.py", line 183, in main
Mar  5 19:52:32 ubuntu le "/usr/local/lib/python3.6/dist-packages/ospd_openvas-20.4a1-py3.6.egg/ospd_openvas/daemon.py", line 322, in init
Mar  5 19:52:32 ubuntu le "/usr/local/lib/python3.6/dist-packages/ospd_openvas-20.4a1-py3.6.egg/ospd_openvas/daemon.py", line 560, in load_vts
Mar  5 19:52:32 ubuntu le "/usr/local/lib/python3.6/dist-packages/ospd_openvas-20.4a1-py3.6.egg/ospd_openvas/nvticache.py", line 133, in get_oids
Mar  5 19:52:32 ubuntu le "/usr/local/lib/python3.6/dist-packages/ospd_openvas-20.4a1-py3.6.egg/ospd_openvas/db.py", line 319, in get_elem_pattern_by_index
Mar  5 19:52:32 ubuntu pd.errors.RequiredArgument: get_elem_pattern_by_index: Argument ctx is required

**Comment by bjoernricks** [comment]
Please paste the full output of what you are trying to do. Currently it isn't reproducible for us. I've just started ospd-openvas from master without any issue.

You PR is definitely not correct because in that case the nvti cache would be read from the the main (0) db of redis.

**Comment by huifeidexingyuner** [comment]
I modified DEFAULT_INDEX to 1, all programs run normally

**Comment by huifeidexingyuner** [comment]
But after I remove all my changes, the program runs normally. So I'm very surprised. Is there a cache or the like as long as it runs normally once?

**Pull request closed without merging**
