### PR TITLE
Add the Notus Metadata Handler as a new module

### PR DESCRIPTION
**Pull request by thorsten-passfeld**
Add handler to upload VT metadata into Redis. This module can also perform checksum checks if needed.

**Checklist**:

- [ ] Tests
- [x] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

### CODE REVIEW

**Review by ArnoStiefvater — CHANGES_REQUESTED** [review]
Tests are missing.

**Comment by jjnicola** [comment]
> Tests are missing.

The test will be added in a second PR.

**Comment by bjoernricks** [comment]
Personally I would move ospd_openvas/notus_metadata_handler.py to ospd_openvas/notus/metadata.py to have a clear distinction.

**Comment by thorsten-passfeld** [comment]
> Personally I would move ospd_openvas/notus_metadata_handler.py to ospd_openvas/notus/metadata.py to have a clear distinction.

Good idea. I just moved it there like you suggested!

**Review by jjnicola — APPROVED** [review]

**Comment by jjnicola** [comment]
Thank you very much @thorsten-passfeld !

**Comment by bjoernricks** [comment]
> > Personally I would move ospd_openvas/notus_metadata_handler.py to ospd_openvas/notus/metadata.py to have a clear distinction.
> 
> Good idea. I just moved it there like you suggested!

Not it is ospd_openvas/notus/notus_metadata_handler.py. Can we change it to ospd_openvas/notus/metadata.py please?

**Pull request merged**
